---
name: darwin-brew-gcc14

on:
  workflow_dispatch:
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: macos-13

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '14.3.1'

      - name: Install Tools
        run: |
          brew update
          brew install gcc@14 make texinfo automake autoconf perl curl coreutils bash

      - name: Compile
        run: ./compile.bash darwin-brew-gcc14
